# Generated by Django 4.2.9 on 2024-01-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0002_alter_dirtydata_id_alter_processeddata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDataCartrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file', models.FileField(upload_to='data_storage/exports/landis/processed_landis/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedDataDME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file', models.FileField(upload_to='data_storage/exports/landis/processed_landis/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedDataKaon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file', models.FileField(upload_to='data_storage/exports/kaon/processed_landis/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFileCartrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom', models.FileField(upload_to='data_storage/dirty_data/uploads/cartrack/excel/')),
                ('pick_n_place', models.FileField(upload_to='data_storage/dirty_text/uploads/cartrack/txt/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFileDME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom', models.FileField(upload_to='data_storage/dirty_data/uploads/DME/excel/')),
                ('pick_n_place', models.FileField(upload_to='data_storage/dirty_text/uploads/DME/txt/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFileKaon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom', models.FileField(upload_to='data_storage/dirty_data/uploads/Kaon/excel/')),
                ('pick_n_place', models.FileField(upload_to='data_storage/dirty_text/uploads/kaon/txt/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFileLandis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom', models.FileField(upload_to='data_storage/dirty_data/uploads/landis/')),
                ('pick_n_place', models.FileField(upload_to='data_storage/text_data/uploads/landis/txt/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFileLG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom', models.FileField(upload_to='data_storage/dirty_data/uploads/landis/')),
                ('pick_n_place', models.FileField(upload_to='data_storage/text_data/uploads/landis/txt/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='dirty_data',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='text_data',
        ),
        migrations.DeleteModel(
            name='DirtyData',
        ),
        migrations.DeleteModel(
            name='ProcessedData',
        ),
        migrations.DeleteModel(
            name='TextData',
        ),
        migrations.AddField(
            model_name='processeddatakaon',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.uploadedfilelandis'),
        ),
        migrations.AddField(
            model_name='processeddatadme',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.uploadedfilelandis'),
        ),
        migrations.AddField(
            model_name='processeddatacartrack',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.uploadedfilelandis'),
        ),
    ]
