# Generated by Django 4.2.9 on 2024-01-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0003_processeddatacartrack_processeddatadme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDataLG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_data', models.FileField(upload_to='data_storage\\exports\\lg')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.uploadedfilelg')),
            ],
        ),
    ]
