# Generated by Django 4.2.9 on 2024-02-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0006_rename_processed_at_processeddatacartrack_processed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processeddatacartrack',
            old_name='file',
            new_name='uploaded_file',
        ),
        migrations.RenameField(
            model_name='processeddatadme',
            old_name='file',
            new_name='uploaded_file',
        ),
        migrations.RenameField(
            model_name='processeddatakaon',
            old_name='file',
            new_name='uploaded_file',
        ),
    ]
