# Generated by Django 4.2.9 on 2024-02-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0007_rename_file_processeddatacartrack_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processeddatacartrack',
            old_name='processed',
            new_name='processed_date',
        ),
        migrations.RenameField(
            model_name='processeddatadme',
            old_name='processed_data',
            new_name='processed_date',
        ),
        migrations.RenameField(
            model_name='processeddatakaon',
            old_name='processed_data',
            new_name='processed_date',
        ),
        migrations.RenameField(
            model_name='uploadedfilekaon',
            old_name='uploaded_data',
            new_name='uploaded_date',
        ),
        migrations.RenameField(
            model_name='uploadedfilelg',
            old_name='uploaded_data',
            new_name='uploaded_date',
        ),
    ]
