# Generated by Django 4.2.9 on 2024-02-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0008_rename_processed_processeddatacartrack_processed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddatadme',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.uploadedfiledme'),
        ),
    ]
