# Generated by Django 4.2.9 on 2024-05-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0009_alter_processeddatadme_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DME_Bom_prooceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom', models.FileField(upload_to='data_storage/dirty_data/uploads/DME/excel/')),
            ],
        ),
        migrations.RenameField(
            model_name='uploadedfiledme',
            old_name='uploaded_data',
            new_name='uploaded_date',
        ),
        migrations.AlterField(
            model_name='processeddatacartrack',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.uploadedfilecartrack'),
        ),
        migrations.AlterField(
            model_name='processeddatadme',
            name='processed_file',
            field=models.FileField(upload_to='data_storage/exports/dme/processed_DME/'),
        ),
        migrations.AlterField(
            model_name='processeddatakaon',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_data.uploadedfilekaon'),
        ),
        migrations.AlterField(
            model_name='uploadedfilekaon',
            name='pick_n_place',
            field=models.FileField(upload_to='data_storage/uploads/dirty_text/kaon/html/'),
        ),
    ]
