# Generated by Django 4.2.9 on 2024-09-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=100, unique=True, verbose_name='Manufacturer Part Number')),
                ('description', models.TextField(blank=True)),
                ('length', models.FloatField(help_text='Length in mm')),
                ('width', models.FloatField(help_text='Width in mm')),
                ('height', models.FloatField(help_text='Height in mm')),
                ('part_name', models.CharField(blank=True, max_length=100)),
                ('part_library_name', models.CharField(blank=True, max_length=100)),
                ('ref', models.CharField(blank=True, max_length=100)),
                ('shape_code', models.CharField(blank=True, max_length=100)),
                ('supply_type', models.CharField(blank=True, max_length=50)),
                ('supply_kind', models.CharField(blank=True, max_length=50)),
                ('tape_kind', models.CharField(blank=True, max_length=50)),
                ('tape_width', models.FloatField(blank=True, null=True)),
                ('tape_pitch', models.FloatField(blank=True, null=True)),
                ('reel_size', models.CharField(blank=True, max_length=50)),
                ('part_count', models.IntegerField(blank=True, null=True)),
                ('supply_direction', models.CharField(blank=True, max_length=50)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('groups', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component_data.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component_data.manufacturer')),
                ('physical_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component_data.physicalclass')),
            ],
        ),
    ]
