# Generated by Django 4.2.9 on 2024-05-22 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_BOMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('LANDIS', 'Landis & Gyr'), ('CARTRACK', ' CarTrack '), ('KAON', 'ETV | Platco'), ('DME', 'Digital matter')], max_length=50, null=True)),
                ('product', models.TextField(max_length=250, null=True)),
                ('date_of_upload', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.programer')),
            ],
        ),
    ]
